### ISSUE TITLE
Proreus duroides/duruoides - Name inconsistency?

### ISSUE THREAD

**Issue by xsainnz** [sfg-taxonpages/dermaptera#1]
https://dermaptera.speciesfile.org/otus/889146/overview lists the species name as _Proreus duroides_ and references "Hebard, M. (1933) Notes on Australasian and Melanesian Dermaptera. Memoirs of the Queensland Museum, 10(3), 145–156." viewing the scanned page here: https://www.biodiversitylibrary.org/page/52130984 the name is spelled with an additional U as _Proreus duruoides_.

**Comment by hhopkins77** [comment]
Mark--thank you for sending this correction and link to citation. This correction has been made.
