### ISSUE TITLE
Anisolabis maidroni is Titanolabis maidroni

### ISSUE THREAD

**Issue by permico** [sfg-taxonpages/dermaptera#12]
Hi Heidi.

Anisolabis maidroni mentioned on DSF actually belongs to Titaonolabis genus.

https://dermaptera.speciesfile.org/otus/890683/overview

Originaly it was described under Homoeolabis genus, then transferred by Popham & Brindle to Anisolabis genus and later by Srivastava in Titanolabis genus.

In Steinmann's World Catalogue of Dermaptera there is no new synonymy established and references to Srivastava's papers are missing, ref:
Anisolabis maindroni (Borelli, 1911) in Steinmann, 1989c: 221-222. Catalog/Collection

In the new artcles about Dermaptera from Southern India species is listed under Titanolabis. References

Karthik, C. M., Kalleshwaraswamy, C. M. (2023): An annotated checklist of earwigs (Dermaptera) of South India with two new records from India. Zootaxa 5330 (4): 561-585, DOI: 10.11646/zootaxa.5330.4.5, URL: http://dx.doi.org/10.11646/zootaxa.5330.4.5
Titanolabis maindroni on page 568

Emiliyamma, K.G., Das, T., Dey, S.L.,Hegde, V.D.(2024).Fauna of India Checklist: Arthropoda: Insecta:
Dermaptera. Version 1.0. Zoological Survey India. July 2024:1-12 DOI: https://doi.org/10.26515/Fauna/1/2023/
Titanolabis maindroni on page 5

I will send you PDFs by email.

Kind regards, 
Boris

**Comment by hhopkins77** [comment]
Thank you Boris. These are entered.
