### ISSUE TITLE
Anisolabis infernalis is Parapsalis infernalis

### ISSUE THREAD

**Issue by permico** [sfg-taxonpages/dermaptera#2]
Can we add subfamily Prolabiscinae, genus Parapsalis and species P.infernalis to DSF?
These 3 taxons are present in GBIF, but missing in Dermaptera species file where this species listed under Anisolabis as per Sakai 1970 interpretation:
https://dermaptera.speciesfile.org/otus/890362/overview
But in GBIF, and as well in many articles and manuals it is under Pygidicranidae. 
https://www.gbif.org/species/4394556
In Srivastava 1998 Fauna of India Pygidicranioidea book there are pictures of sclerites between head and pronotum showing that it is Pygidicranidae, Kamimura 2004 article (see below) also support this placement from molecular biology point of view. it is listed as member of Pygidicranidae.
https://faunaofindia.nic.in/PDFVolumes/fi/024/index.pdf
Here molecular phylogenetic study of Kamimura team showing that P. infernalis belong to Pygidicranoidea and is related to Diplatyidae (Diplatys) and Pygidicranidae (Challia):
https://doi.org/10.1603/0013-8746(2004)097%5B0903:ISOTOO%5D2.0.CO;2
It also needed to add a synonym of this species:
Prolabisca infernalis with following reference:
Nishikawa, M. 1976. Notes on the Prolabiscinae (Dermaptera;
Pygidicranide). Trans. Shikoku Ent. Soc., 13(1-2) : 41-45."

**Comment by hhopkins77** [comment]
Thank you for sending this data to our attention. Please note the following:
--All three of these names are already in DSF. 
--Srivastava 1998 does not move the position of P. infernalis.
--Kamimura 2004 has been added to the workflow--but see comment below.
--Synonym in Nishikawa 1976 has been entered, though it has been overtaken by a later synonymy.
(NB: many papers published between 1990 and 2014 have yet to be entered in DSF. Work is ongoing but current workflow priorities are type and distribution data.)
Thank you again for your contributions and please send any other additions or corrections you may find, especially those outside of the years 1990-2014.

**Comment by permico** [comment]
Hi Heidi
Thank you so much for your reply and support.
Happy that you are back to support DSF.
I see that you added Prolabiscinae on DSF:
https://dermaptera.speciesfile.org/otus/887932/overview
Can you please move Parapsalis species (Parapsalis infernalis and Parapsalis laevis=Prolabisca aroliata) to Pygidicranioidea under that subfamily. This species clearly belongs to Pygidicranioidea by its morphology and molecular data published in Kamimura 2004 and Wipfler 2020. Exact position within Pygidicranioidea needs to be confirmed.
I believe there was miss of Parapsalis infernalis species in Steinmann's books and confusion of its systematic positions in Steinmann's books about this species:
Steinmann, H. (1986) Dermaptera: Catadermaptera I. Das Tierreich, 102, 345 pp. Here Steinmann lists Parapsalis laevis under Echinosomatinae (Pygidicranidae), but no mention of Parapsalis infernalis.
Steinmann, H. (1989b) Dermaptera: Catadermaptera II. Das Tierreich, 105, 505 pp. Here there is no information about Anisolabis infernalis or Parapsalis infernalis. Species ignored.
Srivastava, O. K. 1988. Fauna of India Dermaptera Part-I Superfamily Pygidicranoidea : I-XII + 268 pp. Here Parapsalis infernalis and Parapsalis laevis are synonymized and listed under Prolabiscinae subfamily of Pygidicranidae.
Kamimura Y, Nishikawa M, Yamasako J (2023) DNA barcoding of Japanese earwig species (Insecta, Dermaptera), with sequence diversity analyses of three species of Anisolabididae. Biodiversity Data Journal 11: e107001. https://doi.org/10.3897/BDJ.11.e107001 Here molecular data shows that Parapsalis infernalis (material collected in Japan, so may be P. laevis if synonymy not confirmed) belongs to the same clade as Challia and listed under Pygidicranidae.
Wipfler, Benjamin & Koehler, Ward & Frandsen, Paul & Donath, Alexander & Liu, Shanlin & Machida, Ryuichiro & Misof, Bernhard & Peters, Ralph & Shimizu, Shota & Zhou, Xin & Simon, Sabrina. (2020). Phylogenomics changes our understanding about earwig evolution. Systematic Entomology. 45. 10.1111/syen.12420.  Here it is shown that Parapsalis forms a separate clade within Pygidicranioidea (Karshiellinae was not ananlyzed there, but there is article from Dr. Petr Kocarek showing that Karshiellinae probably is subfamily of Pygidicranidae).
So I think it is reasonable to list Parapsalis under Pygidicranioidea (Prolabiscinae), not Anisolabididae (Anisolabidinae).
In the checklist provided by Masaru Nishikava on Fabian's site (where I also published long time ago checklists for Russia and Ukraine) Parapsalis infernalis is under Prolabscinae (Pygidicranidae).
Kind regards, 
Boris
