### ISSUE TITLE
Timomenus komarovi is Timomenus komarowi

### ISSUE THREAD

**Issue by permico** [sfg-taxonpages/dermaptera#3]
Hi Heidi
It is needed to fix the name of Timomenus komarowi on DSF, which is misspleed as T. komarovi.
https://dermaptera.speciesfile.org/otus/888886/overview lists the species name as Timomenus komarovi (=Opisthocosmia komarovi Semenov, 1901) and references "Semenov, A. (1901) Russkoe entomologiceskoe obozrenie (= Revue Russe d'Entomologie), 1, 98." but viewing the scanned page of original description provided in Latin here: https://www.biodiversitylibrary.org/item/43723#page/122/mode/1up the name is spelled with W as Opisthocosmia komarowi.
There is paper by Russian entomologist Yuri Storozhenko about this issue:
Storozhenko SYu & Paik JC (2009) The correct name of Timomenus komarowi (Semenov, 1901) (Dermaptera: Forficulidae, Opisthocosmiinae) with lectotypification. Far Eastern Entomologist, 199: 7-8.
Paper is available here both in English and Russian:
https://www.biosoil.ru/FEE/Publication/284
This missplelling was already fixed on iNaturalist but unfortunately still persists on DSF may be because it is present in Steinmann books as well.
Kind regards, 
Boris

**Comment by permico** [comment]
I see it is updated already, thank you!

**Comment by hhopkins77** [comment]
Thank you Boris. I have origin or error as Wu 1935. That 2009 paper very helpful!
