### ISSUE TITLE
Prolabiscinae is missing genera and species on DSF

### ISSUE THREAD

**Issue by permico** [sfg-taxonpages/dermaptera#4]
Hi Heidi
I see that you added Prolabiscinae on DSF:
https://dermaptera.speciesfile.org/otus/887932/overview
Thank you so much for it!
Can you please move into that subfamily Parapsalis species (Parapsalis infernalis) and Parapsalis laevis(=Prolabisca aroliata). This species clearly belongs to Pygidicranioidea by its morphology and molecular data published in Kamimura 2004 and Wipfler 2020 (see below). Exact position of this subfamily within Pygidicranioidea is questionable but it is up to your decision (it may be part of Pygidicranidae or form separated clade within Pygidicranioidea). See my reasioning below:
1. Steinmann, H. (1986) Dermaptera: Catadermaptera I. Das Tierreich, 102, 345 pp. Here Steinmann lists Parapsalis laevis under Echinosomatinae (Pygidicranidae), but no mention of Parapsalis infernalis.
2. Steinmann, H. (1989b) Dermaptera: Catadermaptera II. Das Tierreich, 105, 505 pp. Here there is no information about Anisolabis infernalis or Parapsalis infernalis. Species ignored. I believe there was miss of Parapsalis infernalis species in this book that led to further confusion of its systematic positions in Steinmann's books about this species.
3. Srivastava, O. K. 1988. Fauna of India Dermaptera Part-I Superfamily Pygidicranoidea : I-XII + 268 pp. Here Parapsalis infernalis and Parapsalis laevis are synonymized and listed under Prolabiscinae subfamily of Pygidicranidae.
4. Kamimura Y, Nishikawa M, Yamasako J (2023) DNA barcoding of Japanese earwig species (Insecta, Dermaptera), with sequence diversity analyses of three species of Anisolabididae. Biodiversity Data Journal 11: e107001. https://doi.org/10.3897/BDJ.11.e107001 Here molecular data shows that Parapsalis infernalis (material collected in Japan, so may be P. laevis if synonymy not confirmed) belongs to the same clade as Challia and listed under Pygidicranidae.
5. Wipfler, Benjamin & Koehler, Ward & Frandsen, Paul & Donath, Alexander & Liu, Shanlin & Machida, Ryuichiro & Misof, Bernhard & Peters, Ralph & Shimizu, Shota & Zhou, Xin & Simon, Sabrina. (2020). Phylogenomics changes our understanding about earwig evolution. Systematic Entomology. 45. https://doi.org/10.1111/syen.12420.  Here it is shown that Parapsalis forms a separate clade within Pygidicranioidea (Karshiellinae was not ananlyzed there, but there is article from Dr. Petr Kocarek showing that Karshiellinae probably is subfamily of Pygidicranidae).
6. In the checklist provided by Masaru Nishikava on Fabian's site (where I also published long time ago checklists for Russia and Ukraine) Parapsalis infernalis is under Prolabscinae (Pygidicranidae). https://www.earwigs-online.de/JP/jp.html
7. Fauna Sinica: Insecta, Volume 35: Dermaptera 2004 also mentions Parapsalis infernalis under Prolabscinae (Pygidicranidae). I have this book, can send you screenshots if needed.
So I think it is reasonable to list Parapsalis under Pygidicranioidea (Prolabiscinae), not Anisolabidinae as it is now on DSF.
Kind regards, 
Boris

**Comment by hhopkins77** [comment]
Boris, thank you for your kind provision of all this detail. I have made these changes. Can you tell me:
1. the page number in Srivastava 1988 where Parapsalis is listed under Prolabiscinae.
2. I presume he synonymized laevis under infernalis--could you give me a page number for that synonymy.
3. page number in Fauna Sinica on which Parapsalis is listed under Prolabiscinae.

Can you provide an email address where I can reach you regarding possible missing papers in the future?

**Comment by permico** [comment]
Hi Heidi

1. Parapsalis infernalis is listed under Prolabiscinae on p. 6 and pp. 237-241 in Srivastava 1988 book: p. 237 has diagnosis of subfamily Prolabiscinae, p. 238 has diagnosis of genus Parapsalis and pp. 238-241 has description of species Parapsalis infernalis. Figs. 345-351 represent pictures of species. Prolabiscinae subfamily reinstated on p. 23 of this book.
2. Syn. n. is mentioned on page 238 in Srivastava 1988.
3. Fauna Sinica has Parapsalis infernalis under Prolabiscinae on page 81

My email is permico@gmail.com

Kind regards, 
Boris
