### ISSUE TITLE
Allodahlia genus is missing species from China

### ISSUE THREAD

**Issue by permico** [sfg-taxonpages/dermaptera#5]
Hi Heidi

There are several species missing fron DSF which were described from China:
https://dermaptera.speciesfile.org/otus/889005/overview

According to Fauna Sinica: Insecta, Volume 35: Dermaptera 2004 there are at least 2 more species of Allodahlia in China which are not present on DSF. In general there is number of missing species on DSF mostly from China and Madagascar belonging to different genera, I will try to raise tickets later as well.

Allodahlia cheni Sakai et Liu, 1994
Ref.
Sakai et Liu, 1994. Special Bull. Daito Bunka Univ. (1994) No. 45: 5960
Available here:
http://museum.ioz.ac.cn/upload/zhuanti/2017%E6%98%86%E8%99%AB%E6%A8%A1%E5%BC%8F%E6%A0%87%E6%9C%AC/%E5%85%A8%E5%B9%B4%E6%A8%A1%E5%BC%8F%E6%A0%87%E6%9C%AC%E5%8E%9F%E5%A7%8B%E6%96%87%E7%8C%AE/17200179.pdf
Fauna Sinica: Insecta, Volume 35: Dermaptera. Science Press, Beijing, 420 p. P. 307. (I have this book, can send you screenshots if needed).
Type locality: China: Guangxi (Daqingshan).
Distribution according to Fauna Sinica: Guangxi Province, China

Allodahlia dubia Sakai et Liu, 1994
Ref. 
Sakai et Liu, 1994. Special Bull. Daito Bunka Univ. (1994) No. 45: 5959-5960
Available here:
http://museum.ioz.ac.cn/upload/zhuanti/2017%E6%98%86%E8%99%AB%E6%A8%A1%E5%BC%8F%E6%A0%87%E6%9C%AC/%E5%85%A8%E5%B9%B4%E6%A8%A1%E5%BC%8F%E6%A0%87%E6%9C%AC%E5%8E%9F%E5%A7%8B%E6%96%87%E7%8C%AE/17200179.pdf
Fauna Sinica: Insecta, Volume 35: Dermaptera. Science Press, Beijing, 420 p. P. 308.
Type locality: China: Xizang/Tibet Autonomous Region (Medog).
Type photo available here: http://museum.ioz.ac.cn/topic_detail.aspx?id=58494
Distribution according to Fauna Sinica: Xizang/Tibet Autonomous Region, China

Also Liparura sinensis Chen, 1935 was also transferred by Sakai and Liu to Allodahlia genus:
Ref.
Sakai et Liu, 1994. Special Bull. Daito Bunka Univ. (1994) No. 45: 5925
Fauna Sinica: Insecta, Volume 35: Dermaptera. Science Press, Beijing, 420 p. P. 306.
Type locality: China: Guangxi (lingun).
Distribution according to Fauna Sinica: Guangxi Province, China

Kind regards, 

Boris

**Comment by hhopkins77** [comment]
Many papers published between 1990 and 2014 are missing. In some cases because we have no access to the paper or book. I will add these to the workflow.

Whenever you send data, please include page number, if you have access to that info.

If you have pdf of papers, please send to cockroachdoc@gmail.com

**Comment by hhopkins77** [comment]
Do you have title of Sakai and Liu 1994 paper?

**Comment by permico** [comment]
Hi Heidi

Complete reference to that article:

Sakai, Seiroku et Liu, Xian-wei. Notes on the Chinese Alldahlia Verhoeff (1902) with two New species. (Allodahliinae, Forficulidae, Dermaptera). Special Bull. Daito Bunka Univ. (1994) No. 45: 5957-5966

I have added pages to Fauna Sinica citations

**Comment by hhopkins77** [comment]
The transfer of sinensis is on page 5925 (see above). Is that a different paper? Or typo on the page number?

**Comment by permico** [comment]
It is different paper, unfortunately I have no access to it (citation is as per Fauna Sinica).
Complete Reference for Allodahlia sinensis below:
Sakai S, Liu X W and Zhang X C. 1994. Annotated checkist of Dermaptera of China. Special Bull. Daito Bunka Univ. No.45:
3942-5956, in Dermaptera Cat. XXVII. P. 5925

**Comment by permico** [comment]
Thank you again!

**Comment by hhopkins77** [comment]
These changes are all entered.
