### ISSUE TITLE
Missing species in Blandex genus from Madagascar

### ISSUE THREAD

**Issue by permico** [sfg-taxonpages/dermaptera#6]
Hi Heidi.

There is one missing species in Blandex genus on DSF:
https://dermaptera.speciesfile.org/otus/887941/overview

Blandex betschi Jamet, Waller, Albouy & Caussanel, 1999
Type location:
Andringitra massif, Andohariana plateau, Fianarantsoa Province, Madagascar
Distribution:
Madagascar

Reference:

JAMET C., WALLER A., ALBOUY V. & CAUSSANEL C. 1999. — Description d’espèces nouvelles de Dermaptères de Madagascar et mise à jour d’une liste des Dermaptères malgaches. Annales de la Société entomologique de France, N.S., 35 : 71-90. P. 72

I will send you PDF by email.

Kind regards, 

Boris

**Comment by hhopkins77** [comment]
This has been entered.

**Comment by permico** [comment]
Thank you and thank you also for enteraing all other missing species from that publication!
